name: Publish Nuget Package

on: workflow_dispatch

jobs: 
  publish_nuget_package:
    name: Publish
    runs-on: ubutu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pack
        run: |
          dotnet pack ./CICDExapmle_CreateNugetPackage/CICDExapmle_CreateNugetPackage -c  release -o .output
      - name: Publish
        env:
          API_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json